---
- name: Display Role Details.
  debug:
    msg:
      - '===================================================================='
      - 'constrict0r.sysconfig'
      - 'Apply system configuraton.'
      - '===================================================================='

- name: Setting up requirements.
  debug:
    msg:
      - '--------------------------------------------------------------------'
      - 'Main - Processing requirements ...'
      - '--------------------------------------------------------------------'
  when: unified is not variable_empty

- name: Verify requirement installed - git, rsync.
  apt:
    name:
      - git
      - rsync
  when: not ansible_check_mode

- name: Apply skeleton repositories.
  debug:
    msg:
      - '--------------------------------------------------------------------'
      - 'Main - Processing skeleton repositories ...'
      - '--------------------------------------------------------------------'
  when: unified is not variable_empty

- name: Loop through list of skeleton repositories.
  include_tasks: skeleton.yml
  loop: "{{ unified }}"
  loop_control:
    loop_var: current_skeleton
  when: unified is not variable_empty