---
# Tasks to clone skeleton repositories.

- name: Handle Skeleton repositories.
  debug:
    msg:
      - '--------------------------------------------------------------------'
      - 'Processing skeleton ...'
      - '--------------------------------------------------------------------'

- name: Set cloned_source variable.
  set_fact:
    cloned_source: /tmp/cloned_skeleton

- name: Set cloned_destination variable.
  set_fact:
    cloned_destination: /

- name: Clone url.
  debug:
    msg:
      - '____________________________________________________________________'
      - 'Cloning skeleton url ...'
      - '____________________________________________________________________'

- name: Create the cloned_skeleton directory.
  file:
    path: "{{ cloned_source }}"
    state: directory
    force: true
  when: not ansible_check_mode
  changed_when: false

- name: Clone the skeleton repository into cloned_skeleton directory.
  git:
    version: master
    repo: "{{ current_skeleton }}"
    dest: "{{ cloned_source }}"
    accept_hostkey: true
    force: true
  changed_when: false
  when:
    - not ansible_check_mode
    - current_skeleton is variable_url_existent

- name: Verify the process is executing fine.
  debug:
    msg:
      - '____________________________________________________________________'
      - 'Verifying if everything is going well :) ...'
      - '____________________________________________________________________'

- name: Add verification file to source directory.
  file:
    path: "{{ cloned_source }}/.amanita"
    state: touch
  when: not ansible_check_mode
  changed_when: false

- name: Synchronize files.
  debug:
    msg:
      - '____________________________________________________________________'
      - 'Syncing files ...'
      - '____________________________________________________________________'

- name: Synchronize files (Apply configuration).
  synchronize:
    mode: pull
    src: "{{ cloned_source }}/"
    dest: "{{ cloned_destination }}"
    recursive: true
    delete: false
  become: true
  changed_when: false
  delegate_to: "{{ inventory_hostname }}"
  when: not ansible_check_mode

- name: Verify the process is executing fine.
  debug:
    msg:
      - '____________________________________________________________________'
      - 'Verifying if everything is going well :D ...'
      - '____________________________________________________________________'

- name: Get verification file status on destination directory.
  stat:
    path: "{{ cloned_destination }}/.amanita"
  register: st_res
  when: not ansible_check_mode

- name: Verify if files where synchronized.
  fail:
    msg: "Can't synchronize {{ cloned_source }} with {{ cloned_destination }}"
  when:
    - not ansible_check_mode
    - st_res.stat.isreg is undefined or not st_res.stat.isreg | bool

- name: Cleanup.
  debug:
    msg:
      - '____________________________________________________________________'
      - 'Cleaning up files ...'
      - '____________________________________________________________________'

- name: Delete the cloned_skeleton directory.
  file:
    path: "{{ cloned_source }}"
    state: absent
  changed_when: false
  when: not ansible_check_mode

- name: Delete verification file.
  file:
    path: "{{ cloned_destination }}/.amanita"
    state: absent
  become: true
  changed_when: false
  when: not ansible_check_mode